function lfpPerArea = maybe_clean_lfp_artifacts(lfpPerArea, fs, lfpCleanParams)
% MAYBE_CLEAN_LFP_ARTIFACTS - Run clean_lfp_artifacts unless the caller skips it
%
% Variables:
%   lfpPerArea     - [nSamples x nAreas] LFP
%   fs             - Sampling rate (Hz)
%   lfpCleanParams - Arguments for clean_lfp_artifacts. When
%                    .skipArtifactClean is true, the matrix is returned unchanged.
%
% Goal:
%   session_lfp_criticality skips Hampel and spline spike blanking on traces
%   that process_np1_lfp already lowpassed. Other callers still clean.

if isstruct(lfpCleanParams) && isfield(lfpCleanParams, 'skipArtifactClean') ...
        && ~isempty(lfpCleanParams.skipArtifactClean) && lfpCleanParams.skipArtifactClean(1)
    fprintf('Skipping LFP artifact cleaning\n');
    return
end

lfpPerArea = clean_lfp_artifacts(lfpPerArea, fs, ...
    'spikeThresh', lfpCleanParams.spikeThresh, ...
    'spikeWinSize', lfpCleanParams.spikeWinSize, ...
    'notchFreqs', lfpCleanParams.notchFreqs, ...
    'lowpassFreq', lfpCleanParams.lowpassFreq, ...
    'useHampel', lfpCleanParams.useHampel, ...
    'hampelK', lfpCleanParams.hampelK, ...
    'hampelNsigma', lfpCleanParams.hampelNsigma, ...
    'detrendOrder', lfpCleanParams.detrendOrder, ...
    'visualize', false);
end
