{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d1917fc0-06e9-435f-b2df-139ab9965f29",
   "metadata": {},
   "outputs": [],
   "source": [
    "#include <SPI.h>\n",
    "#include <SD.h>\n",
    "#include <string.h>\n",
    "\n",
    "// Pins\n",
    "const int SOLENOID_PORT = 12;\n",
    "const int BEAM_BREAK_PORT = 2;   // active low\n",
    "const int LED_PORT = 10;         // reward confirmation LED\n",
    "\n",
    "// Timing (ms)\n",
    "const int SOLENOID_ON_TIME = 30; //solenoid stays open\n",
    "const int SOLENOID_OFF_TIME = 300; //wait btwn pulses\n",
    "const int SOLENOID_REPEATS = 1; //additional pulses\n",
    "\n",
    "const unsigned long INTERVAL_DURATION = 3000;   // min wait time after confirmed leave\n",
    "const unsigned long MIN_LEAVE_TIME = 100;       // min leave time to confirm exit\n",
    "const unsigned long LED_PULSE = 100;            // reward LED duration (stays on after reward pulse)\n",
    "\n",
    "// SD Card\n",
    "const int chipSelect = 53;\n",
    "File dataFile;\n",
    "char logFileName[50];\n",
    "char buffer[100];\n",
    "\n",
    "// State\n",
    "bool firstPoke = true; //allows first poke to be rewarded\n",
    "\n",
    "bool givingReward = false; //true when solenoid currently open\n",
    "bool inBurst = false; //true when delivering pulses\n",
    "\n",
    "bool leavePending = false; //saw a leave and waiting to confirm 100ms\n",
    "bool timerArmed = false; //true when leave confirmed, waiting for next entry, clock is running\n",
    "\n",
    "int beamState = 0; //current beam value\n",
    "int lastBeamState = 0; //last beam value\n",
    "\n",
    "//timestamp values\n",
    "unsigned long initialExitTime = 0; //when beam was first unbroken\n",
    "unsigned long leaveConfirmStart = 0; //when confirmation window started\n",
    "unsigned long leaveTime = 0; //official start of leave\n",
    "\n",
    "unsigned long rewardStartTime = 0; //when solenoid opened\n",
    "unsigned long lastPulseEndTime = 0; //when previous pulse ended\n",
    "int pulsesGivenInBurst = 0; //counts extra pulses given\n",
    "\n",
    "//LED timing\n",
    "bool ledActive = false;\n",
    "unsigned long ledStartTime = 0;\n",
    "\n",
    "// Logging\n",
    "void logLine(const char* tag, int value) {\n",
    "  if (dataFile) {\n",
    "    sprintf(buffer, \"%lu,%s,%d,\", millis(), tag, value);\n",
    "    dataFile.println(buffer);\n",
    "    dataFile.flush();\n",
    "  }\n",
    "}\n",
    "\n",
    "void writeBeam(int state) { logLine(\"B\", state); } //logs beam transitions\n",
    "void writeReward() { logLine(\"REWARD\", 1); } //logs reward event\n",
    "void writeError() { logLine(\"ERROR\", 1); } //logs error event\n",
    "\n",
    "// Hardware\n",
    "void openSolenoid() {\n",
    "  digitalWrite(SOLENOID_PORT, HIGH);\n",
    "  givingReward = true;\n",
    "  rewardStartTime = millis();\n",
    "}\n",
    "\n",
    "void closeSolenoid() {\n",
    "  digitalWrite(SOLENOID_PORT, LOW);\n",
    "  givingReward = false;\n",
    "  lastPulseEndTime = millis();\n",
    "}\n",
    "\n",
    "void pulseLED() {\n",
    "  digitalWrite(LED_PORT, HIGH);\n",
    "  ledActive = true;\n",
    "  ledStartTime = millis(); //starts led timer\n",
    "}\n",
    "\n",
    "// Setup\n",
    "void setup() {\n",
    "  pinMode(SOLENOID_PORT, OUTPUT);\n",
    "  pinMode(LED_PORT, OUTPUT);\n",
    "  pinMode(BEAM_BREAK_PORT, INPUT);\n",
    "\n",
    "  digitalWrite(SOLENOID_PORT, LOW); //intially solenoid closed\n",
    "  digitalWrite(LED_PORT, LOW); //intially led off\n",
    "\n",
    "  Serial.begin(9600);\n",
    "  SD.begin(chipSelect);\n",
    "\n",
    "  if (!SD.exists(\"interval_task\")) {\n",
    "    SD.mkdir(\"interval_task\");\n",
    "  }\n",
    "\n",
    "  sprintf(logFileName, \"interval_task/log.csv\");\n",
    "  dataFile = SD.open(logFileName, FILE_WRITE);\n",
    "\n",
    "  if (dataFile) {\n",
    "    dataFile.println(\"timestamp_ms,event,value,\");\n",
    "    dataFile.flush();\n",
    "  }\n",
    "}\n",
    "\n",
    "// Loop\n",
    "void loop() {\n",
    "\n",
    "  // Read beam (active low → invert)\n",
    "  beamState = !digitalRead(BEAM_BREAK_PORT); //beam = 1 means mouse inside port and vice versa\n",
    "\n",
    "  // Beam Transitions\n",
    "  if (beamState != lastBeamState) {\n",
    "\n",
    "    writeBeam(beamState);\n",
    "    lastBeamState = beamState;\n",
    "\n",
    "    // Mouse Enters\n",
    "    if (beamState) {\n",
    "\n",
    "      unsigned long now = millis();\n",
    "\n",
    "      // First poke rewarded\n",
    "      if (firstPoke) {\n",
    "        firstPoke = false; //not first poke anymore\n",
    "        writeReward();\n",
    "        inBurst = true; //reward true\n",
    "        pulsesGivenInBurst = 0; //counts pulses\n",
    "        openSolenoid();\n",
    "      }\n",
    "\n",
    "      // After first poke\n",
    "      else if (timerArmed) { //timer is running\n",
    "\n",
    "        if (now - leaveTime >= INTERVAL_DURATION) { //time btwn now and last poke end meets minimum\n",
    "          // SUCCESS\n",
    "          writeReward();\n",
    "          inBurst = true;\n",
    "          pulsesGivenInBurst = 0;\n",
    "          openSolenoid();\n",
    "        } else {\n",
    "          // ERROR\n",
    "          writeError();\n",
    "        }\n",
    "      }\n",
    "\n",
    "      // Any poke resets clock\n",
    "      timerArmed = false;\n",
    "      leavePending = false;\n",
    "    }\n",
    "\n",
    "    // Mouse Leave\n",
    "    else {\n",
    "      leavePending = true; //starts confirmation\n",
    "      initialExitTime = millis();      // true exit moment\n",
    "      leaveConfirmStart = millis();    // start confirmation timer\n",
    "    }\n",
    "  }\n",
    "\n",
    "  // Confirm Leave\n",
    "  if (leavePending) {\n",
    "\n",
    "    if (!beamState && (millis() - leaveConfirmStart >= MIN_LEAVE_TIME)) {\n",
    "    //if unbroken beam and curr - leave time meets minumum leave threshold\n",
    "      leavePending = false;\n",
    "\n",
    "      leaveTime = initialExitTime;   // start interval from true exit\n",
    "      timerArmed = true;\n",
    "    }\n",
    "\n",
    "    // If mouse re-enters before confirm, cancel\n",
    "    if (beamState) {\n",
    "      leavePending = false;\n",
    "    }\n",
    "  }\n",
    "\n",
    "  // Solenoid Pulse\n",
    "  if (givingReward) {\n",
    "    if (millis() - rewardStartTime >= SOLENOID_ON_TIME) {\n",
    "    //if solenoid has been open long enough, closes it\n",
    "      closeSolenoid();\n",
    "    }\n",
    "  }\n",
    "\n",
    "  // Burst Logic\n",
    "  if (inBurst && !givingReward){\n",
    "\n",
    "    if (pulsesGivenInBurst < SOLENOID_REPEATS) {\n",
    "      if (millis() - lastPulseEndTime >= SOLENOID_OFF_TIME) {\n",
    "        openSolenoid();\n",
    "        pulsesGivenInBurst++;\n",
    "        //keeps track of pulses\n",
    "      }\n",
    "    } else {\n",
    "      inBurst = false; //if bursts are done\n",
    "      pulseLED();  // turn on light\n",
    "    }\n",
    "  }\n",
    "\n",
    "  // LED Pulse Timing\n",
    "  if (ledActive && (millis() - ledStartTime >= LED_PULSE)) {\n",
    "    digitalWrite(LED_PORT, LOW);\n",
    "    ledActive = false;\n",
    "  }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb378e50-5b8a-4c79-8eda-6f7a4b689ea0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
