%% Create a README struct to store metadata
README.Description = "Avalanche data and criticality parameters. 43 min each dataset. 1 is all naturalistic data, 2 is all reach task data";
README.DateCreated = datetime('now', 'Format', 'yyyy-MM-dd HH:mm:SS');
README.Source = "xxxxxxx";
README.Variables = struct( ...
    'optBinSize', 'Bin size of data (s)', ...
    'Av', 'Avalanche data (brain area X natural/reach)', ...
    'tau_and_tauC', 'size distribution log-log parameter (tauC is cutoff tau)', ...
    'alpha', 'duration distribution parameter', ...
    'sigmaNuZInvSD', 'size vs. duration parameter', ...
    'brHist', 'PDF historgrams of branching ratios', ...
    'centers', 'center of bins in brHist' ...
);
README.Notes = "addnoteshere.";

%% Save README along with data
save('dataFile.mat', 'README', 'dataMat', 'bhvID', 'svmID', 'projSelect');