%% Create a README struct to store metadata
README.Description = "Structures of classic criticality parameters. See criticality_script.m. Reach (R) and Naturualistic (N) data for binsizes equal between areas or optimized (Opt) for each area (M23 M56 DS VS, respectively)";
README.DateCreated = datetime('now', 'Format', 'yyyy-MM-dd HH:mm:SS');
% README.Source = "xxxxxxx";
README.Variables = struct( ...
    'brPeak', 'histogram of branching ratios (across avalanches)', ...
    'brMr', 'branching ratio using branching_ratio_mr_estimation.m', ...
    'tau', 'size distribution parameter', ...
    'tauC', 'size distribution parameter with ends cut off', ...
    'alpha', 'duration distribution parameter', ...
    'paramSD', 'size vs distribution parameter with ends cut off', ...
    'decades', 'how many orders of magnitude size scales across', ...
    'kappa', 'distance to criticality (see compute_kappa.m)', ...
    'dcc', 'distance to criticality using tau (see distance_to_criticality.m)', ...
    'dccC', 'distance to criticality using tauC (see distance_to_criticality.m)', ...
    'optBinSize', 'bin size per area' ...
);
% README.Notes = "addnoteshere.";

%% Save README along with data
% save('dataFile.mat', 'README', 'dataMat', 'bhvID', 'svmID', 'projSelect');

%% Append README 
save([paths.dropPath, 'criticality_sliding_classic.mat'], 'README', '-append');
